### ISSUE TITLE
Liquidate not triggering auction

### ISSUE THREAD

**Issue by bette7** [AcalaNetwork/Acala#107] opened 2020-02-11 08:07 UTC
When liquidating an unsafe loan, collateral_balance is 0, and no additional auction events.

<img width="843" alt="Screen Shot 2020-02-10 at 2 52 17 PM" src="https://user-images.githubusercontent.com/42193328/74219592-1f69d100-4d12-11ea-830c-d93434928a4d.png">

**Comment by wangjj9219** [comment] 2020-02-11 12:33
This fault is actually caused by lacking of check for zero debit_balance when try to liquidate a cdp with 0 collateral amount ：https://github.com/AcalaNetwork/Acala/blob/21f35d42124f19d998eca467f0b16d79586fc219/modules/cdp_engine/src/lib.rs#L288-L301

The bug will be fixed soon.

**Closed** 2020-02-11 21:04 UTC
Labels: bug
